[package]
name = "trollface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
image = "0.24.5"
lazy_static = "1.4.0"
open = "3.4.0"
rand = "0.8.5"
reqwest = "0.11.14"
rodio = "0.17.1"
tokio = { version = "1", features = ["full"] }

[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_Graphics_Gdi"
]
